### ISSUE TITLE
tests require admin access on windows 10 to create symlinks.

### ISSUE THREAD

**Issue by Aladdin-ADD** [not-an-aardvark/eslint-plugin-eslint-plugin#10]
**node version: v8.1.2**
**npm version: 5.0.3**

![image](https://user-images.githubusercontent.com/13050025/27746659-a9e5214a-5dfa-11e7-90e3-e80f166dd951.png)

**Comment by Aladdin-ADD** [comment]
should run as admin, closing.

**Comment by not-an-aardvark** [comment]
Hmm, it seems like it's not a good idea to require the tests to be run as admin. I'll reopen this to try to find a better solution.
