### ISSUE TITLE
Support ESLint 8.x

### ISSUE THREAD

**Issue by MichaelDeBoey** [not-an-aardvark/eslint-plugin-eslint-plugin#175]
ESLint v8.0.0 is [released](https://eslint.org/blog/2021/10/eslint-v8.0.0-released) 🎉

It would be awesome to have official ESLint 8 support. 👊
I'm happy to help where I can of course 🙂

---

- [x] https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/pull/119
- [x] https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/pull/151
- [ ] https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/pull/186

**Comment by aladdin-add** [comment]
to clarify: the eslint has already supported eslint v8. I just prepared a PR https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/pull/186 to add tests for it.

**Comment by aladdin-add** [comment]
no worries, we will try to release v4 in 2~3 days.
