### ISSUE TITLE
`require-meta-schema` should only autofix when no options present

### ISSUE THREAD

**Issue by bmish** [not-an-aardvark/eslint-plugin-eslint-plugin#182]
> The goal is that the rule should only autofix to `schema: []` if no options are used.

_Originally posted by @bmish in https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/pull/180#discussion_r715251282_

**Comment by aladdin-add** [comment]
the autofix will introduce a breaking change for users passing unknown options:

before autofix: skip validating and lint working fine.
after autofix: an error thrown from eslint.
