### ISSUE TITLE
Plugin requires "parserOptions.sourceType" being configured to "script"

### ISSUE THREAD

**Issue by tristanHessell** [not-an-aardvark/eslint-plugin-eslint-plugin#244]
Rules in this repo have a dependency on eslint being configured with:

```
...
parserOptions: {
  sourceType: 'script',
}
```

This is makes sense, but I ran into unexpectedly as I created a plugin from scratch rather than using the yeoman generator (https://github.com/eslint/generator-eslint).
For context, using the generator `eslint-plugin-node/recommended` gets extended and this config sets the parserOption).

Can we update the documentation somewhere to make it clear that this is a configuration requirement?

I'm happy to create a PR to update `README.md` with this.

**Comment by aladdin-add** [comment]
not sure I got your point.

is it related to `eslint-plugin-eslint-plugin`? or `eslint-plugin-node`?

**Comment by tristanHessell** [comment]
`eslint-plugin-eslint-plugin`.

The short answer is that the plugin requires `parserOptions.sourceType` to be `script` to work and that isn't documented (unless im mistaken).

I'm more than happy to contribute a PR to add to the documentation if we see fit.

**Comment by aladdin-add** [comment]
sure, PRs are always welcome! 👍

**Comment by aladdin-add** [comment]
Yes, setting the parserOptions works. I'll update the plugin to also check `undefined` - it should also fix the issue.

**Comment by bmish** [comment]
One important note here: as mentioned at the top of our [README](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin#eslint-plugin-eslint-plugin---), eslint-plugin-eslint-plugin can work on all CJS/ESM/TypeScript repos, so either `script` or `module` can be used with us.

There were some general improvements I wanted to make to the usage example in the README, so I opened a PR, and also mentioned `parserOptions.sourceType` in it. Please comment on the PR and let me know if that addresses your concern.

**Comment by bmish** [comment]
Our plug-in doesn't specifically care what sourceType is. I think what he's running into is just general eslint syntax parsing issues.

**Comment by tristanHessell** [comment]
@bmish I think you hit the nail on the head.

I'll add a comment to the PR as you asked 👍
