### ISSUE TITLE
`require-meta-type` don't support spread operator

### ISSUE THREAD

**Issue by piranna** [not-an-aardvark/eslint-plugin-eslint-plugin#250]
When filling `meta` object using a spread operator instead of explicitly set the fields, the eslint validator fails. It should look for the content of the spread and see that the required fields are there, instead of forcing to set them explicitly.

**Comment by bmish** [comment]
I have a PR in progress #251 for this that should be finished in the next few days.

**Comment by piranna** [comment]
Great! :D
