### ISSUE TITLE
Detect suggestions with spread variable in `require-meta-has-suggestions`

### ISSUE THREAD

**Issue by bmish** [not-an-aardvark/eslint-plugin-eslint-plugin#281]
Related of #272 but distinct and might be a bit easier to fix since we just need to evaluate the spread.

```js
const fixOrSuggest: {
  fix: TSESLint.ReportFixFunction | null;
  suggest: TSESLint.ReportSuggestionArray<MessageIds> | null;
} = {
  fix: null,
  suggest: [
    {
      messageId: 'suggestUnknown',
      fix(fixer): TSESLint.RuleFix {
        return fixer.replaceText(node, 'unknown');
      },
    },
    {
      messageId: 'suggestNever',
      fix(fixer): TSESLint.RuleFix {
        return fixer.replaceText(node, 'never');
      },
    },
  ],
};

if (fixToUnknown) {
  fixOrSuggest.fix = (fixer): TSESLint.RuleFix =>
    fixer.replaceText(node, 'unknown');
}

context.report({
  node,
  messageId: 'unexpectedAny',
  ...fixOrSuggest,
});
```

https://github.com/typescript-eslint/typescript-eslint/blob/ad412cdd74dc5619fbe4bf27c0a5eb5c5a4b65ca/packages/eslint-plugin/src/rules/no-explicit-any.ts#L205

This is not specific to TypeScript.

**Comment by JoshuaKGoldberg** [comment]
This might be another case like #283 🤔 . What if a rule calls to a helper function to report with suggestions? Same strategy as https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/issues/283#issuecomment-1211489294?
