### ISSUE TITLE
False positive with `no-unused-message-ids` when violation reporting is done with external helper function

### ISSUE THREAD

**Issue by bmish** [not-an-aardvark/eslint-plugin-eslint-plugin#283]
In this example, the `context.report()` calls are all in a separate helper file, so we can't detect that the `messageId`s are used.

We should ignore this situation where we can't find any `context.report()` calls.

https://github.com/typescript-eslint/typescript-eslint/blob/b6e5413fb12c2b1943a288b514f864c339380388/packages/eslint-plugin/src/rules/naming-convention.ts#L11

**Comment by aladdin-add** [comment]
I've encountered the issue in `eslint-plugin-node` as well: https://github.com/weiran-zsd/eslint-plugin-node/blob/d7b975a07e1b876ca2c75597d054a81564b25685/lib/rules/no-unsupported-features/es-builtins.js#L173-L179

it's really helpful to ignore these cases, at least it can be an option. 👍

**Comment by JoshuaKGoldberg** [comment]
> We should ignore this situation where we can't find any context.report() calls.

Edge case: a rule that calls `context.report()` for some message IDs, but calls to an external function for other message IDs.

Suggestion: how about disabling when the rule can see that a value set to `context` or its `validate` property is passed to a function?

**Comment by aladdin-add** [comment]
> a value set to context or its validate property is passed to a function?

it sounds we were guessing the user's wants, while it's not always reliable. I'm 👍  to @bmish 's suggestion.

**Comment by bmish** [comment]
> > We should ignore this situation where we can't find any `context.report()` calls.
> 
> Edge case: a rule that calls `context.report()` for some message IDs, but calls to an external function for other message IDs.
> 
> Suggestion: how about disabling when the rule can see that a value set to `context` or its `validate` property is passed to a function?

That's definitely a valid edge case. Regarding your suggestion, I'm open to it as a further improvement, especially if we start seeing real-world examples of that edge case, but note that there could be false negatives from it. Also we would want to limit that suggestion to external/imported functions that we can't analyze.
