### ISSUE TITLE
Rule proposal: require-meta-docs-url

### ISSUE THREAD

**Issue by mysticatea** [not-an-aardvark/eslint-plugin-eslint-plugin#55]
Since https://github.com/eslint/eslint/pull/9788, `meta.docs.url` is the official place to show the link to rule documentation. It would be good if there is a rule to enforce to write the link. Additionally, it's awesome if the rule is fixable.

```json
{
    "eslint-plugin/require-meta-docs-url": [
        "error",
        { "pattern": "https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/blob/master/docs/rules/{{name}}.md" }
    ]
}
```

- `pattern` (`string`) ... the URL pattern. Default is undefined. If this option is specified, the rule fixes `meta.docs.url` automatically. It replaces the `{{name}}` placeholder to rule name (`path.basename(context.getFilename(), ".js")`).

**Comment by platinumazure** [comment]
This could replace ESLint's internal `consistent-docs-url` rule, too.
