### ISSUE TITLE
Cannot use function invocation with `require-meta-docs-url`

### ISSUE THREAD

**Issue by sudo-suhas** [not-an-aardvark/eslint-plugin-eslint-plugin#58]
The rule `require-meta-docs-url` cannot be used with a function invocation as done here - [mysticatea/eslint-plugin-node:lib/rules/exports-style.js@`bbf4b60`#L302](https://github.com/mysticatea/eslint-plugin-node/blob/bbf4b6032705d446cd3532c92649fdc2894da9d1/lib/rules/exports-style.js#L302):

```
`meta.docs.url` property must be a string. (eslint-plugin/require-meta-docs-url)
```

Would it be possible to fix this issue?

**Comment by not-an-aardvark** [comment]
I don't think it's possible to fix this because there is no way to tell what your `getDocsUrl` function does. That said, if you're already using a helper function to get the docs URL, it might be better to just disable the rule.

**Comment by sudo-suhas** [comment]
Alright, thanks!
