### ISSUE TITLE
require-meta-type does not work if `create` is not a function

### ISSUE THREAD

**Issue by MrHen** [not-an-aardvark/eslint-plugin-eslint-plugin#83]
The following does not fail linting:

```
/* eslint eslint-plugin/require-meta-type: error */

function create(context) {
	// ...
}

module.exports = {
	meta: {}, // should fail
	create
};
```

----

```
/* eslint eslint-plugin/require-meta-type: error */

const create = (context) => {
	// ...
}

module.exports = {
	meta: {}, // should fail
	create
};
```

----

It looks like the utility for checking if a file contains a rule has a [hard check](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/blob/master/lib/utils.js#L93) for `create` being a function. Is this check necessary? Can I submit a PR to either:

* Allow identifiers on the right side of `create` even if they are not functions?
* Or follow identifiers on the right side of `create` if they reference a function in the same file?

**Comment by aladdin-add** [comment]
> * Allow identifiers on the right side of create even if they are not functions?
> * Or follow identifiers on the right side of create if they reference a function in the same file?

personally I prefer the second, but I'm fine either way.  PRs are welcome! 😄

**Comment by MrHen** [comment]
Awesome, I should have time this week to whip something up.
