### ISSUE TITLE
Support ESLint 7.x

### ISSUE THREAD

**Issue by MichaelDeBoey** [not-an-aardvark/eslint-plugin-eslint-plugin#94]
ESLint v7.0.0 is [released](https://eslint.org/blog/2020/05/eslint-v7.0.0-released) 🎉

It would be awesome to have official ESLint 7 support. 👊
I'm happy to help where I can of course 🙂

**Comment by MichaelDeBoey** [comment]
I've seen #92, but this fails CI:
https://travis-ci.org/github/not-an-aardvark/eslint-plugin-eslint-plugin

**Comment by not-an-aardvark** [comment]
Thanks for the issue/PR. Does the plugin not support ESLint v7 already? In theory it seems like it shouldn't need any changes unless it was affected by a breaking change in ESLint.

**Comment by MichaelDeBoey** [comment]
@not-an-aardvark It does, but CI breaks on Node 6, 8 & 9, like you can see on https://travis-ci.org/github/not-an-aardvark/eslint-plugin-eslint-plugin/builds/672563685.

#95 fixes this, but that would mean a breaking change

**Comment by martis-git** [comment]
Still actual!))
